# Generated by Django 5.2.14 on 2026-05-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='hashtags',
            field=models.TextField(blank=True, help_text='해시태그들을 저장합니다.', null=True),
        ),
    ]
