# Generated by Django 5.2.14 on 2026-05-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_review_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image_url',
            field=models.TextField(blank=True, help_text='장소 대표 이미지의 URL 주소.', null=True),
        ),
    ]
