# Generated by Django 6.0.6 on 2026-06-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_placeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeanalysis',
            name='ad_probability',
            field=models.IntegerField(default=50, verbose_name='non ad probability'),
        ),
    ]
