"""
Django settings for placed_backend project.

Generated by 'django-admin startproject' using Django 4.x.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 실제 배포 시에는 환경변수로 관리하거나 변경해야 합니다.
SECRET_KEY = 'django-insecure-change-this-key-for-production-usage'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # [추가된 라이브러리]
    'rest_framework',       # API 구축용 프레임워크
    'corsheaders',          # React(3000포트)와 통신 허용을 위한 CORS 헤더
    'api',                  # 우리가 생성한 핵심 기능 앱
]

MIDDLEWARE = [
    # [CORS 미들웨어 추가 - 최상단 배치 권장]
    'corsheaders.middleware.CorsMiddleware',
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# [CORS 설정]
# React 개발 서버(localhost:3000)에서의 접근을 허용합니다.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]
CORS_ALLOW_CREDENTIALS = True


ROOT_URLCONF = 'placed_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'placed_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'  # 한국어 설정

TIME_ZONE = 'Asia/Seoul' # 한국 시간대 설정

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# [커스텀 사용자 모델 설정]
# api앱의 User 모델을 기본 인증 모델로 사용하도록 지정합니다.
AUTH_USER_MODEL = 'api.User'


# [Gemini API 키 설정]
# 구글 AI Studio에서 발급받은 API 키를 입력하세요.
# 보안을 위해 실제 서비스 시에는 os.environ.get('GEMINI_API_KEY') 형태로 환경변수를 사용하는 것이 좋습니다.
GEMINI_API_KEY = "AIzaSyCnTi-Jz11HJ8Dx88-Tev8RWi1QIA_BijQ"

GEMINI_MODEL_NAME = "gemini-2.5-flash-lite"